--! Q1
-- SELECT 
--     DISTINCT job_schedule_type,
--     AVG(salary_year_avg) AS avg_annual,
--     AVG(salary_hour_avg) AS avg_hourly
-- FROM job_postings_fact
-- WHERE (job_posted_date::DATE > '2023-06-01')
--     AND (job_schedule_type != '')
-- GROUP BY job_schedule_type
-- HAVING AVG(salary_year_avg) > 0 AND AVG(salary_hour_avg) > 0
--!Q2
-- SELECT
--     DISTINCT EXTRACT(
--         MONTH FROM 
--         job_posted_date AT TIME ZONE 'UTC' AT TIME ZONE 'EST'
--         ) AS month,
--     COUNT(job_id)
-- FROM job_postings_fact
-- WHERE EXTRACT(YEAR FROM job_posted_date) = '2023'
-- GROUP BY month
--!Q3
-- SELECT
--     company_dim.name AS company_name,
--     job_posted_date::DATE
-- FROM job_postings_fact
-- JOIN company_dim ON job_postings_fact.company_id = company_dim.company_id
-- WHERE job_health_insurance = TRUE
--     AND
--     (job_posted_date::DATE >= '2023-04-01' AND job_posted_date::DATE < '2024-01-01')
-- GROUP BY company_dim.name, job_posted_date::DATE
-- ORDER BY job_posted_date::DATE